server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5_SIMPLY
      - ANDROID_VR
      - IOS
      - WEBEMBEDDED

  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false
    spotify:
      clientId: "c5c0d8acbf6c4851af70cff2bff3aafb"
      clientSecret: "813d32b826cc47cfb2bdc10a5e294528"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    applemusic:
      countryCode: "US"
      mediaAPIToken: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldlYlBsYXlLaWQifQ.eyJpc3MiOiJBTVBXZWJQbGF5IiwiaWF0IjoxNjg4MDQ4ODE5LCJleHAiOjE2OTU4MjQ4MTksInJvb3RfaHR0cHNfb3JpZ2luIjpbImFwcGxlLmNvbSJdfQ.r_CMw1xbBu7O1eWPBOCMwFNw3xfNy1PtHe4PaYQHPZN0yQEcILqzQf1A3NcFVlvDzGnlKhKQC2VxnwDvjB3k3A"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    deezer:
      masterDecryptionKey: "your_master_decryption_key_here"

logging:
  level:
    root: INFO
    lavalink: INFO
    com.github.topi314.lavasrc: DEBUG
    dev.lavalink.youtube: DEBUG
  file:
    name: logs/lavalink.log
    max-size: 50MB
    max-history: 7