server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 800
    frameBufferDurationMs: 1000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 100

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5_SIMPLY_EMBEDDED_PLAYER
      - ANDROID_VR
      - IOS
      - WEBEMBEDDED
    WEB:
      playback: true
    TVHTML5_SIMPLY_EMBEDDED_PLAYER:
      playback: true

  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
    spotify:
      clientId: "c5c0d8acbf6c4851af70cff2bff3aafb"
      clientSecret: "813d32b826cc47cfb2bdc10a5e294528"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6

logging:
  level:
    root: INFO
    lavalink: INFO
    com.github.topi314.lavasrc: DEBUG
    dev.lavalink.youtube: DEBUG
  file:
    name: logs/lavalink.log
    max-size: 50MB
    max-history: 7